Repository Turing-Cross-Pol/DispersedCamping_BE, pull requests merged in 2020-05, with the labels that each got.

#19 Nk/testing 1
  .travis.yml
  tests/test_campsite.py
  tests/test_sample.py
  venv/pyvenv.cfg
Labels: enhancement

#38 Add amenity create and read interaction
  app/__init__.py
  app/models.py
  migrations/versions/9c1d8774e51f_.py
  test_campsite.py
Labels: database, feature

#44 Bug in comments where rating was over ridden by description
  app/__init__.py
  manage.py
Labels: bug
